ci/cd: 배포 작업에서 오류 발생 시 로그를 확인하고 종료
- 배포 작업에서 오류 발생 시 로그를 확인합니다.
- 배포가 성공했는지 확인합니다.
- 로그를 확인하고 종료합니다.
- 배포가 성공했을 경우 메시지를 출력합니다.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,7 +8,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    retries: 3 # 배포를 자동으로 재시도할 횟수
 
     steps:
       - name: Checkout repository
@@ -89,3 +88,13 @@ jobs:
           region: ap-northeast-2
           deployment_package: deploy/deploy.zip
           use_existing_version_if_available: true
+        continue-on-error: true
+
+      - name: Check Deployment Status
+        run: |
+          if [ "$?" != "0" ]; then
+            echo "Deployment failed. Please check the logs."
+            exit 1
+          else
+            echo "Deployment succeeded."
+          fi
